// Mocks generated by Mockito 5.4.2 from annotations
// in todo_app/test/domain/usecases/task_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/domain/entities/local/task_entity.dart' as _i4;
import 'package:todo_app/domain/repositories/task_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i2.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insertTaskEntity({required _i4.TaskEntity? task}) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTaskEntity,
          [],
          {#task: task},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.TaskEntity>> getTaskEntity({
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaskEntity,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<_i4.TaskEntity>>.value(<_i4.TaskEntity>[]),
      ) as _i3.Future<List<_i4.TaskEntity>>);

  @override
  _i3.Future<int> updateTaskEntity({required _i4.TaskEntity? task}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskEntity,
          [],
          {#task: task},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteTaskEntity({required String? key}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTaskEntity,
          [],
          {#key: key},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
